# Copyright (c) 2018, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version=environ.get('CONDA_PY', 36) %}
{% set cuda_version='.'.join(environ.get('CUDA_VERSION', '10.1').split('.')[:2]) %}

package:
  name: cuxfilter
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - VERSION_SUFFIX

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - cudf {{ minor_version }}
    - cuspatial {{ minor_version }}
    - dask-cudf {{ minor_version }}
    - dask-cuda {{ minor_version }}
    - datashader >=0.11.1
    - numba >=0.51.2
    - cupy  >=6*
    - panel >=0.9.*
    - bokeh >=2.1.1
    - pyproj  >=2.4.*
    - geopandas >=0.6.*
    - nodejs >=14.9.0
    - libwebp
    - pyppeteer
    - jupyter-server-proxy
    - pydeck >=0.3.*

test:
  requires:
    - cudatoolkit {{ cuda_version }}.*
  commands:
    - python -c "import cuxfilter"

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: GPU accelerated cross filtering with cuDF
